### ISSUE TITLE
Game crashes when I try to launch it with the mod

### ISSUE THREAD

**Issue by SwedishAddict** [cpw/inventorysorter#143]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022-07-27, 22:30
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.111-universal.jar%23216!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.111-universal.jar%23216!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:justzoom.mixin.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23211!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.111.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD inventorysorter --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$MouseScrollEvent$Post
		at cpw.mods.inventorysorter.InventorySorter.clientSetup(InventorySorter.java:85) ~[inventorysorter-1.19-20.0.0.jar%23174!/:20.0.0] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.111.jar%23213!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.0.111.jar%23212!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/strid/AppData/Roaming/.minecraft/mods/inventorysorter-1.19-20.0.0.jar
	Failure message: Simple Inventory Sorter (inventorysorter) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$MouseScrollEvent$Post
	Mod Version: 20.0.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ScreenEvent$MouseScrollEvent$Post
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.inventorysorter.InventorySorter.clientSetup(InventorySorter.java:85) ~[inventorysorter-1.19-20.0.0.jar%23174!/:20.0.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.111.jar%23213!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.0.111.jar%23212!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 691779072 bytes (659 MiB) / 2558525440 bytes (2440 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 96302,84
	Virtual memory used (MB): 15523,83
	Swap memory total (MB): 80000,00
	Swap memory used (MB): 492,48
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G
	Loaded Shaderpack: (off)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		inventorysorter-1.19-20.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |20.0.0              |ERROR     |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Forge-1.0.1-1.19.jar                              |Additional Entity Attributes  |additionalentityattributes    |1.0.1+1.19          |ENQUEUE_IM|Manifest: NOSIGNATURE
		ellemes-container-library-2.0.4+1.19-forge.jar    |Ellemes' Container Library    |ellemes_container_lib         |2.0.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.222.jar                     |Just Enough Items             |jei                           |11.0.0.222          |ENQUEUE_IM|Manifest: NOSIGNATURE
		extendedslabs-1.19-2.2.0.jar                      |Extended Slabs +              |extendedslabs                 |2.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		AttributeFix-Forge-1.19-15.0.2.jar                |AttributeFix                  |attributefix                  |15.0.2              |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-windows-2.0.3-mc1.19.jar                      |Macaw's Windows               |mcwwindows                    |2.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		caelus-forge-1.19-3.0.0.3.jar                     |Caelus API                    |caelus                        |1.19-3.0.0.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		apoli-forge-1.19-2.3.4.2.jar                      |Apoli                         |apoli                         |1.19-2.3.4.2        |ENQUEUE_IM|Manifest: NOSIGNATURE
		sophisticatedcore-1.19-0.4.5.78.jar               |Sophisticated Core            |sophisticatedcore             |1.19-0.4.5.78       |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium-0.6.0b.jar                               |Rubidium                      |rubidium                      |0.6.0b              |ENQUEUE_IM|Manifest: NOSIGNATURE
		kleeslabs-forge-1.19-12.0.0.jar                   |KleeSlabs                     |kleeslabs                     |12.0.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		RingsOfAscension-1.19-1.0.1.jar                   |Rings of Ascension            |ringsofascension              |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Neat-1.8-31.jar                                   |Neat                          |neat                          |1.8-31              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Fallingleaves-1.19-1.3.0-beta.1.jar               |Falling Leaves                |fallingleaves                 |1.3.0-beta.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Clumps-forge-1.19-9.0.0+3.jar                     |Clumps                        |clumps                        |9.0.0+3             |ENQUEUE_IM|Manifest: NOSIGNATURE
		Controlling-forge-1.19-10.0+3.jar                 |Controlling                   |controlling                   |10.0+3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-1.12.6-1.19.jar                           |Citadel                       |citadel                       |1.12.6              |ENQUEUE_IM|Manifest: NOSIGNATURE
		alexsmobs-1.19.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.19.3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		NaturesCompass-1.19-1.9.7-forge.jar               |Nature's Compass              |naturescompass                |1.19-1.9.7-forge    |ENQUEUE_IM|Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |ENQUEUE_IM|Manifest: NOSIGNATURE
		More+Babies-forge-1.19-0.5.3.jar                  |More Babies                   |more_babies                   |0.5.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.18.4.648.jar        |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.18.4.648     |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.19.jar                        |Macaw's Doors                 |mcwdoors                      |1.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ExplorersCompass-1.19-1.2.3-forge.jar             |Explorer's Compass            |explorerscompass              |1.19-1.2.3-forge    |ENQUEUE_IM|Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.19-(v.4.0.1).jar     |Additional Structures         |additionalstructures          |4.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-4.4.0.jar                                    |Balm                          |balm                          |4.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.19-2.0.3.jar                  |FPS Reducer                   |fpsreducer                    |1.19-2.0.3          |ENQUEUE_IM|Manifest: NOSIGNATURE
		carryon-1.19-1.18.1.2.jar                         |Carry On                      |carryon                       |1.18.1.2            |ENQUEUE_IM|Manifest: NOSIGNATURE
		cloth-config-7.0.73-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.73              |ENQUEUE_IM|Manifest: NOSIGNATURE
		soundphysics-forge-1.19-1.0.9.jar                 |Sound Physics Remastered      |sound_physics_remastered      |1.19-1.0.9          |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19-41.0.111-universal.jar                 |Forge                         |forge                         |41.0.111            |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		konkrete_forge_1.4.0_MC_1.19.jar                  |Konkrete                      |konkrete                      |1.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-paths-1.0.0-mc1.19.jar                        |Macaw's Paths and Pavings     |mcwpaths                      |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		infernalmobs-1.19.2.jar                           |Infernal Mobs                 |infernalmobs                  |1.19.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AdvancementPlaques-1.19-1.4.4.jar                 |Advancement Plaques           |advancementplaques            |1.4.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.19.jar                      |Macaw's Bridges               |mcwbridges                    |2.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		repurposed_structures_forge-6.1.3+1.19.jar        |Repurposed Structures         |repurposed_structures         |6.1.3+1.19          |ENQUEUE_IM|Manifest: NOSIGNATURE
		theoneprobe-1.19-6.2.0.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.0          |ENQUEUE_IM|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |ENQUEUE_IM|Manifest: NOSIGNATURE
		physics-mod-2.8.2-mc-1.19-forge.jar               |Physics Mod                   |physicsmod                    |2.8.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		PlayerPlates-1.0.2-build.11+mc1.19.jar            |Player Plates                 |playerplates                  |1.0.2-build.11+mc1.1|ENQUEUE_IM|Manifest: NOSIGNATURE
		ToolBelt-1.19-1.19.6.jar                          |Tool Belt                     |toolbelt                      |1.19.6              |ENQUEUE_IM|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.6-mc1.19.jar                    |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.19.jar                       |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |ENQUEUE_IM|Manifest: NOSIGNATURE
		movingelevators-1.3.9-forge-mc1.19.jar            |Moving Elevators              |movingelevators               |1.3.9               |ENQUEUE_IM|Manifest: NOSIGNATURE
		calio-forge-1.19-1.6.0.2.jar                      |Calio                         |calio                         |1.19-1.6.0.2        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Iceberg-1.19-1.0.45.jar                           |Iceberg                       |iceberg                       |1.0.45              |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.4.jar                     |Curios API                    |curios                        |1.19-5.1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Patchouli-1.19-75.jar                             |Patchouli                     |patchouli                     |1.19-75             |ENQUEUE_IM|Manifest: NOSIGNATURE
		origins-forge-1.19-1.5.0.4-fatjar.jar             |Origins                       |origins                       |1.19-1.5.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.5_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.11.5             |ENQUEUE_IM|Manifest: NOSIGNATURE
		oculus-mc1.19-1.2.5a.jar                          |Oculus                        |oculus                        |1.2.5a              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Quark-3.3-beta-367.jar                            |Quark                         |quark                         |3.3-beta-367        |ENQUEUE_IM|Manifest: NOSIGNATURE
		OreExcavation-1.11.165.jar                        |OreExcavation                 |oreexcavation                 |1.11.165            |ENQUEUE_IM|Manifest: NOSIGNATURE
		InventoryHud_[1.19].forge-3.4.6.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.0-2.7.4.jar                    |Gobber 2                      |gobber2                       |2.7.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		expandedstorage-8.0.2+1.19-forge.jar              |Expanded Storage              |expandedstorage               |8.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.19-1.0.6.jar             |BetterFurnaces Reforged       |betterfurnacesreforged        |1.19-1.0.6          |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-5.10.33-forge.jar                    |Architectury                  |architectury                  |5.10.33             |ENQUEUE_IM|Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |ENQUEUE_IM|Manifest: NOSIGNATURE
		justzoom_forge_1.0.1-1_MC_1.19.jar                |Just Zoom                     |justzoom                      |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		charmofundying-forge-6.0.0-beta.2+1.19.jar        |Charm of Undying              |charmofundying                |6.0.0-beta.2+1.19   |ENQUEUE_IM|Manifest: NOSIGNATURE
		Aquaculture-1.19-2.4.4.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.4          |ENQUEUE_IM|Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |ENQUEUE_IM|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19-v2a.jar                |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19-v2a            |ENQUEUE_IM|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		UncraftingTable-1.19-forge-1.0.5.3.jar            |Uncrafting Table              |uncraftingtable76             |1.0.5.3             |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.19.jar                       |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 8df684c3-c31b-4a27-a506-7369dae5d337
	FML: 41.0
	Forge: net.minecraftforge:41.0.111

**Comment by cpw** [comment]
Fixed with latest, tho you need 1.19.2
