### ISSUE TITLE
NeoForge 21.0.86 loading mod error

### ISSUE THREAD

**Issue by Mike-057** [cpw/inventorysorter#191]
Hi, mod is incompatible with NeoForege 21.0.86

Log:
```
Time: 2024-07-12 10:50:58
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at TRANSFORMER/neoforge@21.0.86-beta/net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:57) ~[neoforge-21.0.86-beta-universal.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.86-beta/net.neoforged.neoforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:127) ~[neoforge-21.0.86-beta-universal.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.buildInitialScreens(Minecraft.java:673) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.onGameLoadFinished(Minecraft.java:646) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.onResourceLoadFinished(Minecraft.java:641) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.lambda$new$7(Minecraft.java:629) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.Util.ifElse(Util.java:513) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.lambda$new$8(Minecraft.java:623) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.86-beta/net.neoforged.neoforge.client.loading.NeoForgeLoadingOverlay.render(NeoForgeLoadingOverlay.java:145) ~[neoforge-21.0.86-beta-universal.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1081) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1198) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:810) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23116!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23116!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/inventorysorter@24.0.4/cpw.mods.inventorysorter.Config.register(Config.java:74) ~[inventorysorter-1.21-24.0.4.jar%23183!/:24.0.4] {re:classloading}
-- MOD inventorysorter --
Details:
	Mod File: /C:/Users/micha/curseforge/minecraft/Instances/modtest/mods/inventorysorter-1.21-24.0.4.jar
	Failure message: fml.modloadingissue.failedtoloadmod
	Mod Version: 24.0.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'net.neoforged.fml.config.IConfigSpec net.neoforged.neoforge.common.ModConfigSpec.self()'
Stacktrace:
	at TRANSFORMER/inventorysorter@24.0.4/cpw.mods.inventorysorter.Config.register(Config.java:74) ~[inventorysorter-1.21-24.0.4.jar%23183!/:24.0.4] {re:classloading}
	at TRANSFORMER/inventorysorter@24.0.4/cpw.mods.inventorysorter.InventorySorter.<init>(InventorySorter.java:71) ~[inventorysorter-1.21-24.0.4.jar%23183!/:24.0.4] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.18.jar%23101!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 91519416 bytes (87 MiB) / 564133888 bytes (538 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 28
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-14700K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.42
	Number of physical packages: 1
	Number of physical CPUs: 20
	Number of logical CPUs: 28
	Graphics card #0 name: NVIDIA GeForce RTX 4070 Ti SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 16376.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 69373.01
	Virtual memory used (MiB): 13986.31
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 1239117.88, total: 1906842.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1239117.88, total: 1906842.00
	Space in storage for io.netty.native.workdir (MiB): available: 1239117.88, total: 1906842.00
	Space in storage for java.io.tmpdir (MiB): available: 1239117.88, total: 1906842.00
	Space in storage for workdir (MiB): available: 1239117.88, total: 1906842.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.14.0+mixin.0.8.6.jar mixin PLUGINSERVICE 
		loader-4.0.18.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.18.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.18.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		client-1.21-20240613.152323-srg.jar               |Minecraft                     |minecraft                     |1.21                |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		inventorysorter-1.21-24.0.4.jar                   |Simple Inventory Sorter       |inventorysorter               |24.0.4              |Manifest: NOSIGNATURE
		neoforge-21.0.86-beta-universal.jar               |NeoForge                      |neoforge                      |21.0.86-beta        |Manifest: NOSIGNATURE
	Crash Report UUID: eba4e300-9e4c-4b7e-a003-dd664403bc71
	FML: 4.0.18
	NeoForge: 21.0.86-beta
```

**Comment by Mike-057** [comment]
After update everything works fine :)
