### ISSUE TITLE
Console error invalid plugin.yml

### ISSUE THREAD

**Issue by axemwa** [cpw/inventorysorter#57]
[16:49:51 ERROR]: Could not load 'plugins\inventorysorter-1.12.2-1.13.3+57.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1451]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.2.jar:git-Paper-1451]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) [patched_1.12.2.jar:git-Paper-1451]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) [patched_1.12.2.jar:git-Paper-1451]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1451]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by axemwa** [comment]
oopz sorry I forgot to close it, didn't realize it was still open
