### ISSUE TITLE
1.14.4 crash on server startup, Forge-28.1.1 incompatibility.

### ISSUE THREAD

**Issue by Wissi** [cpw/inventorysorter#75]
Great mod but it's crashing server on startup.
Just needs to be coded for newest Forge.
Full debug.log [here](https://gist.github.com/Wissi/895ed2c98a09a1ae11684ef55826ee33).

Using:  inventorysorter-1.14.4-15.2.0.jar 
```
net.minecraftforge.fml.ModLoadingException: Mod File inventorysorter-1.14.4-15.2.0.jar needs language provider javafml:28 to load
§7We have found 28.1
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:63) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_221]
	at java.util.Collections$2.tryAdvance(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[12Sep2019 15:57:17.541] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: null
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:165) ~[?:?]
```
Using: inventorysorter-1.14.4-15.3.0-ms.0.1+40a82c3.jar
```
[12Sep2019 16:20:12.010] [Server thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File inventorysorter-1.14.4-15.3.0-ms.0.1+40a82c3.jar needs language provider javafml:28 to load
§7We have found 28.1
```

using:
forge-28.1.1
inventorysorter-1.14.4-15.2.0.jar 
and also with:
inventorysorter-1.14.4-15.3.0-ms.0.1+40a82c3.jar

**Comment by Gbergz** [comment]
Can confirm aswell, same error. Forge 28.1.1 & 28.1.0

**Comment by raziel23x** [comment]
![image](https://user-images.githubusercontent.com/441966/64873398-f637fe00-d616-11e9-8912-abe469d03e4e.png)

**Comment by Gamertech** [comment]
New update's working just fine. Thanks

**Comment by Wissi** [comment]
Yes it is, new version:

`inventorysorter-1.14.4-16.0.0.jar`  &  `Forge-28.1.1`

Fixes the issue and are working fine now.
I'll close this.
Thanks.
