### ISSUE TITLE
cant run getting this problem javafml 28?

### ISSUE THREAD

**Issue by jcdriftekv2** [cpw/inventorysorter#76]

**Comment by Riddler76** [comment]
With new version of forge 28.1.1 have this error when starting the game :

 Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File inventorysorter-1.14.4-15.3.0-ms.0.1+40a82c3.jar needs language provider javafml:28 to load
§7We have found 28.1
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:63) ~[?:?]
	at net.minecraftforge.fml.ModLoadingException$$Lambda$1940/1000871406.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_51]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:114) ~[?:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:143) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:79) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1934/1240091493.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1935/1257669532.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:79) [?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:453) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.1.jar:28.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$313/399653041.call(Unknown Source) [forge-1.14.4-28.1.1.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?]

**Comment by raziel23x** [comment]
![image](https://user-images.githubusercontent.com/441966/64868137-c126ae00-d60c-11e9-9ead-089102cded5d.png)

**Comment by rebelpanda** [comment]
To fix this before the author get a chance to update, you just need a program that can open archive files. I use 7-zip for this.

So for me,  I opened the archive with 7-zip (right click > 7-zip > Open Archive), then opened META-INF, right clicked mods.toml, and clicked edit. From there, find the line starting with: loaderVersion="[28]" and changed it to loaderVersion="[28,)".

Game hasn't given me any issues since!

**Comment by cpw** [comment]
LOL. I'm the best!

**Comment by jcdriftekv2** [comment]
ok ty!!!!!

**Comment by raziel23x** [comment]
i did this to make it simple here a pull request i did that fixes it for me in my fork https://github.com/cpw/inventorysorter/pull/77

**Comment by Parker101200** [comment]
> To fix this before the author get a chance to update, you just need a program that can open archive files. I use 7-zip for this.
> 
> So for me, I opened the archive with 7-zip (right click > 7-zip > Open Archive), then opened META-INF, right clicked mods.toml, and clicked edit. From there, find the line starting with: loaderVersion="[28]" and changed it to loaderVersion="[28,)".
> 
> Game hasn't given me any issues since!

This also works for me.  Can't use it on my realm though :(

**Comment by cpw** [comment]
Not an issue for newer versions.
