### ISSUE TITLE
Doesn't work at all on server 

### ISSUE THREAD

**Issue by Ahnaf-Ahmed** [cpw/inventorysorter#82]
Using forge 28.1.0, the mod doesn't work at all in a server, trying it in a chest didn't work either.. In a single player world it only works when inside a chest

**Comment by turret001** [comment]
I'm also struggling with this issue. Does not work on Multiplayer at all, works just fine in single player.

**Comment by Kaitlyn-S** [comment]
This is crashing my server as well - /accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE

**Comment by cpw** [comment]
It works fine for me on forgecraft and locally.

**Comment by turret001** [comment]
I'm on a 1.14.4 spigot server. I thought inventory sorting would've been like inv tweaks mod

**Comment by Drtrider** [comment]
Also seeing the mod not work while on multiplayer servers that don't have the mod.

**Comment by JavierPAYTEF** [comment]
It throws the following error in forge-1.14.4-28.1.0 when running on a server.

`[17:55:10] [modloading-worker-2/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: java.lang.NoClassDefFoundError: net/minec
raftforge/fml/network/simple/SimpleChannel$MessageBuilder$ToBooleanBiFunction
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2365/1309129637@6cce9485
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/fml/network/simple/SimpleChannel$MessageBuilder$ToBooleanBiFunction

        at cpw.mods.inventorysorter.Network.<clinit>(Network.java:73)
        at cpw.mods.inventorysorter.InventorySorter.preinit(InventorySorter.java:112)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
        at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:133)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/network/simple/SimpleChannel$MessageBuilder$ToBooleanBiFunction
        ... 20 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.network.simple.SimpleChannel$MessageBuilder$ToBooleanBiFunction
        at java.lang.ClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more`

**Comment by cpw** [comment]
Not compatible with Forge RB, sorry.

**Comment by JavierPAYTEF** [comment]
What's RB? Did you remove the compatibility? Previous version 16.0.0 was working fine, except sorting player inventory. I just reverted to that version for now and I'm using it without player inventory
