### ISSUE TITLE
Crashes on latest Forge build 1.16.1-32.0.71

### ISSUE THREAD

**Issue by msaroka** [cpw/inventorysorter#96]
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
	at cpw.mods.inventorysorter.InventorySorter.onServerStarting(InventorySorter.java:117) ~[?:17.0.0] {re:classloading}
	at cpw.mods.inventorysorter.InventorySorter$$Lambda$3032/488502364.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2801/498023236.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:65) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$4885/1071793776.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1166981632 bytes (1112 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.71.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.71
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.71-client.jar Minecraft {minecraft@1.16.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		forge-1.16.1-32.0.71-universal.jar Forge {forge@32.0.71 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:inventorysorter (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by msaroka** [comment]
The new version does not crash for me.  Thanks.

**Comment by TeamDman** [comment]
New version doesn't crash for me, but doesn't work in multiplayer. Didn't check on SP.
